apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubeapp-rtp
  namespace: kubeapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app:  kubeapp-rtp
  template:
    metadata:
      labels:
        app:  kubeapp-rtp
    spec:
      imagePullSecrets:
      - name: jfrogcred
      containers:
      - name:  kubeapp-rtp
        image: volun2k9.jfrog.io/vol2k9-docker-local/volun2k9app:0.1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
        - name: CONSUMER_KEY
          value: "G6lmKhsi0V9TvXt6oKTfjRBCr"
        - name: CONSUMER_SECRET
          value: "bEyDk8X0p8SQd4376eoNV4nH8To22sHcJOoFt0ZqOKS37hhI4q"
        - name: ACCESS_TOKEN
          value: "9703354-52rXHD6EeOQeYyhtNz1w8UVOgbcLcgOo4O7MB6WV3"
        - name: ACCESS_TOKEN_SECRET
          value: "zBThlZDEp8qnu7NwwdHNth8eg3Rf9zqbvUEFUTaZtN2SF"
